### ISSUE TITLE
What kind of vcf file use in input

### ISSUE THREAD

**Issue by pailloufat-stack** [tpbilton/GUSrelate#2]
Hi,

Thanks for developping that tool.

I wonder about the kind of vcf file use in input, because the `simDS.vcf.ra.tab` does not have a "common" genotype format. I mean, in the first row for example : 

```
1       866499  25,0    0,2     9,0     1,0     5,0     7,0     5,7     4,0     13,0    18,0    6,0     9,0     3,0     6,0     1,0     0,0     16,0    5,7     7,2     1,1     15,9    4,7     2,0     5,0     2,2 1,1      6,0     25,0    9,12    21,0    5,0     3,5     39,0    6,0     5,2     4,0     0,0     9,5     13,0    6,0     8,0     0,1     9,7     21,0    5,5     10,0    5,0     8,0     3,0     26,0    5,1     15,03,1      8,16    11,0    4,1     5,4     17,0    7,5     8,8     1,8     2,1     8,0     3,1     2,4     4,0     3,0     23,0    11,0    4,0     0,0     2,2     30,0    11,0    5,5     13,5    7,0     41,0    3,0 28,0     1,3     1,0     19,19   3,0     13,0    0,4     2,7     10,14   12,0    2,4     0,2     9,8     12,0    32,0    8,0     5,0     12,0    5,0     9,15    6,1     2,3     0,1     0,0     1,0
```

It looks like a diploïd vcf file with x/x genotype format, except for the `15,03,1` sample which is 3n? I assume a 3n sample is x/x/x. 

I guess the 0/0 samples are reference homozygous? And what about the values >1 ? Because I will have triploïd and then, my matrix file will be with calls as 0, 1, 2, 3 only.

Best

**Comment by tpbilton** [comment]
Hi,

GUSrelate does take a VCF file but first converts it to an RA (reference/alternative) allele count format. So for the entries `simDS.vcf.ra.tab`, the first number is the number of reads for the reference allele and the second number is the number of reads for the alternate allele. 

For example, an entry `5,7` means that there are 5 reads for the reference allele and 7 reads for the alternate allele.

Note that an entry "0,0" is that no reads have been seen for either allele and so is essentially a missing genotype. GUSrelate can handle missing genotypes ok.

Note that the software is assuming bi-allelic SNPs and so there should only be two alleles. This is regardless of ploidy level.

Hope this helps.

Timothy

**Comment by pailloufat-stack** [comment]
Hi Timothy,

Thanks for your quick feedback. 

Indeed, the RA format makes sense now. That was pretty obvious actually. Anyway, all is clear for me now. 

GUSrelate will help for future projects, not my next one because some of my 3n samples might be tri-allelic. 

Best regards,
Paillou

**Comment by tpbilton** [comment]
Hi Paillou,

Great, thanks for clarifying that made sense.

For multi-allelic SNPs, one possible solution would be to convert them into multiple biallelic SNPs. For example, if there were three alleles in a SNP, then create two biallelic SNPs, where the first SNP is the presence or absence of the first allele and the second SNP is the presence or absence of the second allele (note that there should always be one biallelic SNP less than the number of alleles in the original multi-allelic SNP).

Just a suggestion in case you can't find any other way to handle multi-allelic SNPs.

Cheers,
Timothy

**Comment by pailloufat-stack** [comment]
Hi Timothy,

Well! Thanks for the tip. I'll take your advice on board and try to apply it to a test dataset already because for the time being, my samples have not yet been genotyped.

I'll keep you updated on what I get.

Best,
Paillou
